# Generated by Django 2.0.2 on 2018-02-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20180209_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspc',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='businesspc',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
