# Generated by Django 2.0.2 on 2018-02-15 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20180215_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='image_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
