# Generated by Django 2.0 on 2018-02-20 05:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('backend', '0014_productdetails_data_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Category',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSalesTeam',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=1000)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('login_count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Category',
                'ordering': ('email',),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=1000)),
                ('part_no', models.CharField(max_length=1000)),
                ('specification_details', models.CharField(max_length=1000)),
                ('processor', models.CharField(max_length=1000)),
                ('screen_size', models.CharField(blank=True, max_length=1000, null=True)),
                ('warranty', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=1000)),
                ('hard_disk', models.CharField(max_length=1000)),
                ('operating_system', models.CharField(blank=True, max_length=1000, null=True)),
                ('screen', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField()),
                ('graphics', models.CharField(blank=True, max_length=1000, null=True)),
                ('odd', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.CharField(max_length=100)),
                ('modified', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('image_url', models.URLField(max_length=1000)),
                ('data_sheet', models.URLField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='Partner',
        ),
        migrations.DeleteModel(
            name='BaseUser',
        ),
        migrations.AddField(
            model_name='partnersalesteam',
            name='dealer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Partner'),
        ),
    ]
