# Generated by Django 2.0.2 on 2018-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20180220_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product',), 'verbose_name_plural': 'Product'},
        ),
        migrations.AlterField(
            model_name='partnersalesteam',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
    ]
