# Generated by Django 2.0.2 on 2018-02-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20180222_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.NullBooleanField(default=True),
        ),
    ]
