# Generated by Django 2.0.3 on 2018-03-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20180222_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.CharField(blank=True, max_length=100, null=True)),
                ('modified', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.CharField(blank=True, max_length=100, null=True)),
                ('modified', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Type',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='partnersalesteam',
            options={'ordering': ('email',), 'verbose_name_plural': 'Partner Sales Team'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(to='backend.ProductType'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_type',
            field=models.ManyToManyField(to='backend.UserType'),
        ),
    ]
