# Generated by Django 2.0 on 2018-04-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20180403_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersalesteam',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=0, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[('CHINESE', 'CHINESE'), ('SPANISH', 'SPANISH'), ('ENGLISH', 'ENGLISH'), ('FRENCH', 'FRENCH'), ('HINDI', 'HINDI'), ('ARABIC', 'ARABIC'), ('RUSSIAN', 'RUSSIAN')], default=2, verbose_name='Language'),
        ),
    ]
