# Generated by Django 2.0 on 2018-04-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20180403_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desciption',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
