# Generated by Django 2.0.2 on 2018-02-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20180209_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspc',
            name='created',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='businesspc',
            name='modified',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='created',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='modified',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='created',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='modified',
            field=models.CharField(max_length=100),
        ),
    ]
