# Generated by Django 2.0.2 on 2018-02-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20180209_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Notebook', 'Notebook'), ('BusinessPC', 'BusinessPC'), ('Workstation', 'Workstation')], max_length=20)),
                ('product', models.CharField(max_length=1000)),
                ('part_no', models.CharField(max_length=1000)),
                ('specification_details', models.CharField(max_length=1000)),
                ('processor', models.CharField(max_length=1000)),
                ('screen_size', models.CharField(blank=True, max_length=1000, null=True)),
                ('warranty', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=1000)),
                ('hard_disk', models.CharField(max_length=1000)),
                ('operating_system', models.CharField(blank=True, max_length=1000, null=True)),
                ('screen', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.CharField(max_length=1000)),
                ('graphics', models.CharField(blank=True, max_length=1000, null=True)),
                ('odd', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.CharField(max_length=100)),
                ('modified', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessPC',
        ),
        migrations.DeleteModel(
            name='NoteBook',
        ),
        migrations.DeleteModel(
            name='WorkStation',
        ),
    ]
